In [2]:
'''
Team 9: Erick Leyva, Priyanshi Vaishnav, Rose Navarrete, and Justin Girgis
CECS 451
February 06, 2020

'''

import numpy as np
import random


class Board:
    def __init__(self, n):
        self.n_queen = n
        self.map = [[0 for j in range(n)] for i in range(n)]
        self.fit = 0
        self.encode = ""
        self.perc = 0

    def set_queens(self):
        for i in range(self.n_queen):
            j = random.randint(0, self.n_queen - 1)
            self.map[i][j] = 1

    def fitness(self):
        self.fit = self.n_queen * (self.n_queen - 1) // 2
        for i in range(self.n_queen):
            for j in range(self.n_queen):
                if self.map[i][j] == 1:
                    for k in range(1, self.n_queen - i):
                        if self.map[i + k][j] == 1:
                            self.fit -= 1
                        if j - k >= 0 and self.map[i + k][j - k] == 1:
                            self.fit -= 1
                        if j + k < self.n_queen and self.map[i + k][j + k] == 1:
                            self.fit -= 1

    def encoding(self):
        for row in self.map:
            for col in range(self.n_queen):
                if row[col] == 1:
                    self.encode += str(col)
                    break

    def show(self):
        print(np.matrix(self.map))
        print("Fitness: ", self.fit)

In [4]:
'''
Team 9: Erick Leyva, Priyanshi Vaishnav, Rose Navarrete, and Justin Girgis
CECS 451
February 06, 2020

'''

import Board
import random


class Genetic:
    def __init__(self, n):
        self.step = 0
        self.boards = [Board.Board(n) for _ in range(8)]
        max_fit = self.boards[0].n_queen * (self.boards[0].n_queen - 1) // 2
        fits = [0]
        self.steps = 0
        for board in self.boards:
            board.set_queens()
            board.fitness()
            board.encoding()
        while max(fits) != max_fit:
            self.selection()
            for x in range(8):
                self.mutation(self.boards[x])
            self.update_boards()
            fits = []
            for board in self.boards:
                board.fitness()
                fits.append(board.fit)
            self.steps += 1
        ind = fits.index(max(fits))
        print("Number of steps: " + str(self.steps))
        self.boards[ind].show()

    def update_boards(self):
        for board in self.boards:
            for row in range(len(board.encode)):
                board.map[row] = [0 for _ in range(len(board.map[row]))]
                board.map[row][int(board.encode[row])] = 1

    def selection(self):
        # fitSum=0
        total = 0
        for board in self.boards:
            total += board.fit
        for board in self.boards:
            board.perc = board.fit / total
        pairs = []
        for i in range(8):
            r = random.random()
            if r < self.boards[0].perc:
                pairs.append(self.boards[0])
            elif r > self.boards[0].perc and r < self.boards[0].perc + self.boards[1].perc:
                pairs.append(self.boards[1])
            elif r > self.boards[0].perc + self.boards[1].perc and r < self.boards[0].perc + self.boards[1].perc + self.boards[2].perc:
                pairs.append(self.boards[2])
            elif r > self.boards[0].perc + self.boards[1].perc + self.boards[2].perc and r < self.boards[0].perc + self.boards[1].perc + self.boards[2].perc + self.boards[3].perc:
                pairs.append(self.boards[3])
            elif r > self.boards[0].perc + self.boards[1].perc + self.boards[2].perc + self.boards[3].perc and r < self.boards[0].perc + self.boards[1].perc + self.boards[2].perc + self.boards[3].perc + self.boards[4].perc:
                pairs.append(self.boards[4])
            elif r > self.boards[0].perc + self.boards[1].perc + self.boards[2].perc + self.boards[3].perc + self.boards[4].perc and r < self.boards[0].perc + self.boards[1].perc + self.boards[2].perc + self.boards[3].perc + self.boards[4].perc + self.boards[5].perc:
                pairs.append(self.boards[5])
            elif r > self.boards[0].perc + self.boards[1].perc + self.boards[2].perc + self.boards[3].perc + self.boards[4].perc + self.boards[5].perc and r < self.boards[0].perc + self.boards[1].perc + self.boards[2].perc + self.boards[3].perc + self.boards[4].perc + self.boards[5].perc + self.boards[6].perc:
                pairs.append(self.boards[6])
            else:
                pairs.append(self.boards[7])
        self.crossover(pairs[0], pairs[1])
        self.crossover(pairs[2], pairs[3])
        self.crossover(pairs[4], pairs[5])
        self.crossover(pairs[6], pairs[7])

    def crossover(self, A, B):
        cpoint = random.randint(0, A.n_queen - 1)
        right = A.encode[cpoint:]
        A.encode = A.encode[0:cpoint] + B.encode[cpoint:]
        B.encode = B.encode[:cpoint] + right

    def mutation(self, board):
        index = random.randint(0, board.n_queen-1)
        board.encode = board.encode[:index] + str(random.randint(0, board.n_queen-1)) + board.encode[index + 1:]


if __name__ == '__main__':
    g = Genetic(5)

    # home = Board.Board(5)
    # s = HillClimb.Hill_Climb(home)
    # s.board.show()
    # s.solve_board()
    # s.board.show()
    # g = Genetic(4)
    # st = "324231"

Number of steps: 7
[[0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]]
Fitness:  10


In [5]:
'''
Team 9: Erick Leyva, Priyanshi Vaishnav, Rose Navarrete, and Justin Girgis
CECS 451
February 06, 2020

'''

from Board import Board


class HillClimb:
    def __init__(self, board):
        self.step = 0
        self.N = 5000
        self.board = board
        self.board.set_queens()
        self.board.fitness()
        self.map = self.board.map

    def solve_board(self):
        ideal_fit = self.board.n_queen * (self.board.n_queen - 1) // 2
        j = 0
        n = 0
        while self.board.fit != ideal_fit:
            if n > self.N:
                j = 0
                n = 0
                self.board.map = [[0 for j in range(self.board.n_queen)] for i in range(self.board.n_queen)]
                self.board.set_queens()
                self.map = self.board.map
            j = 0 if j == 4 else j
            self.fits = [_ for _ in range(self.board.n_queen)]  # list comprehension
            # for x in range(self.board.n_queen):
            #     self.fits[x] = x
            for i in range(self.board.n_queen):
                self.move_queen(j, i)
                self.board.fitness()
                self.fits[i] = self.board.fit
            index = self.fits.index(max(self.fits))
            self.move_queen(j, index)
            self.board.fitness()
            j += 1
            n += 1

    def move_queen(self, row, col):
        for x in range(self.board.n_queen):
            if self.board.map[row][x] == 1:
                self.board.map[row][x] = 0
        self.board.map[row][col] = 1


if __name__ == "__main__":
    home = Board(5)
    s = HillClimb(home)
    s.board.show()
    s.solve_board()
    s.board.show()


[[0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 1 0 0 0]]
Fitness:  5
[[0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]]
Fitness:  10
